//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/ComputeComponentDigest.schema.json
var schemaComputeComponentDigest []byte

//go:embed schemas/ComputeComponentDigestOutput.schema.json
var schemaComputeComponentDigestOutput []byte

//go:embed schemas/ComputeComponentDigestSpec.schema.json
var schemaComputeComponentDigestSpec []byte

// JSONSchema returns the JSON Schema for ComputeComponentDigest.
func (ComputeComponentDigest) JSONSchema() []byte {
	return schemaComputeComponentDigest
}

// JSONSchema returns the JSON Schema for ComputeComponentDigestOutput.
func (ComputeComponentDigestOutput) JSONSchema() []byte {
	return schemaComputeComponentDigestOutput
}

// JSONSchema returns the JSON Schema for ComputeComponentDigestSpec.
func (ComputeComponentDigestSpec) JSONSchema() []byte {
	return schemaComputeComponentDigestSpec
}
