//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/UTF8Input.schema.json
var schemaUTF8Input []byte

//go:embed schemas/UTF8InputOutput.schema.json
var schemaUTF8InputOutput []byte

//go:embed schemas/UTF8InputSpec.schema.json
var schemaUTF8InputSpec []byte

// JSONSchema returns the JSON Schema for UTF8Input.
func (UTF8Input) JSONSchema() []byte {
	return schemaUTF8Input
}

// JSONSchema returns the JSON Schema for UTF8InputOutput.
func (UTF8InputOutput) JSONSchema() []byte {
	return schemaUTF8InputOutput
}

// JSONSchema returns the JSON Schema for UTF8InputSpec.
func (UTF8InputSpec) JSONSchema() []byte {
	return schemaUTF8InputSpec
}
