//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.35. DO NOT EDIT.

package v1alpha1

import (
	constructorv2 "ocm.software/open-component-model/bindings/go/constructor/v1"
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UTF8Input) DeepCopyInto(out *UTF8Input) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(UTF8InputSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(UTF8InputOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UTF8Input.
func (in *UTF8Input) DeepCopy() *UTF8Input {
	if in == nil {
		return nil
	}
	out := new(UTF8Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *UTF8Input) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UTF8InputOutput) DeepCopyInto(out *UTF8InputOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UTF8InputOutput.
func (in *UTF8InputOutput) DeepCopy() *UTF8InputOutput {
	if in == nil {
		return nil
	}
	out := new(UTF8InputOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UTF8InputSpec) DeepCopyInto(out *UTF8InputSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(constructorv2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UTF8InputSpec.
func (in *UTF8InputSpec) DeepCopy() *UTF8InputSpec {
	if in == nil {
		return nil
	}
	out := new(UTF8InputSpec)
	in.DeepCopyInto(out)
	return out
}
