//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/HelmInput.schema.json
var schemaHelmInput []byte

//go:embed schemas/HelmInputOutput.schema.json
var schemaHelmInputOutput []byte

//go:embed schemas/HelmInputSpec.schema.json
var schemaHelmInputSpec []byte

// JSONSchema returns the JSON Schema for HelmInput.
func (HelmInput) JSONSchema() []byte {
	return schemaHelmInput
}

// JSONSchema returns the JSON Schema for HelmInputOutput.
func (HelmInputOutput) JSONSchema() []byte {
	return schemaHelmInputOutput
}

// JSONSchema returns the JSON Schema for HelmInputSpec.
func (HelmInputSpec) JSONSchema() []byte {
	return schemaHelmInputSpec
}
