//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.35. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeComponentDigest) DeepCopyInto(out *ComputeComponentDigest) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(ComputeComponentDigestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(ComputeComponentDigestOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeComponentDigest.
func (in *ComputeComponentDigest) DeepCopy() *ComputeComponentDigest {
	if in == nil {
		return nil
	}
	out := new(ComputeComponentDigest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *ComputeComponentDigest) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeComponentDigestOutput) DeepCopyInto(out *ComputeComponentDigestOutput) {
	*out = *in
	out.Digest = in.Digest
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeComponentDigestOutput.
func (in *ComputeComponentDigestOutput) DeepCopy() *ComputeComponentDigestOutput {
	if in == nil {
		return nil
	}
	out := new(ComputeComponentDigestOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeComponentDigestSpec) DeepCopyInto(out *ComputeComponentDigestSpec) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpectedDigest != nil {
		in, out := &in.ExpectedDigest, &out.ExpectedDigest
		*out = new(v2.Digest)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeComponentDigestSpec.
func (in *ComputeComponentDigestSpec) DeepCopy() *ComputeComponentDigestSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeComponentDigestSpec)
	in.DeepCopyInto(out)
	return out
}
