//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/DirInput.schema.json
var schemaDirInput []byte

//go:embed schemas/DirInputOutput.schema.json
var schemaDirInputOutput []byte

//go:embed schemas/DirInputSpec.schema.json
var schemaDirInputSpec []byte

// JSONSchema returns the JSON Schema for DirInput.
func (DirInput) JSONSchema() []byte {
	return schemaDirInput
}

// JSONSchema returns the JSON Schema for DirInputOutput.
func (DirInputOutput) JSONSchema() []byte {
	return schemaDirInputOutput
}

// JSONSchema returns the JSON Schema for DirInputSpec.
func (DirInputSpec) JSONSchema() []byte {
	return schemaDirInputSpec
}
