//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.35. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirInput) DeepCopyInto(out *DirInput) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DirInputSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(DirInputOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirInput.
func (in *DirInput) DeepCopy() *DirInput {
	if in == nil {
		return nil
	}
	out := new(DirInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *DirInput) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirInputOutput) DeepCopyInto(out *DirInputOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirInputOutput.
func (in *DirInputOutput) DeepCopy() *DirInputOutput {
	if in == nil {
		return nil
	}
	out := new(DirInputOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirInputSpec) DeepCopyInto(out *DirInputSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeFiles != nil {
		in, out := &in.ExcludeFiles, &out.ExcludeFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeFiles != nil {
		in, out := &in.IncludeFiles, &out.IncludeFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirInputSpec.
func (in *DirInputSpec) DeepCopy() *DirInputSpec {
	if in == nil {
		return nil
	}
	out := new(DirInputSpec)
	in.DeepCopyInto(out)
	return out
}
