//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/FileInput.schema.json
var schemaFileInput []byte

//go:embed schemas/FileInputOutput.schema.json
var schemaFileInputOutput []byte

//go:embed schemas/FileInputSpec.schema.json
var schemaFileInputSpec []byte

// JSONSchema returns the JSON Schema for FileInput.
func (FileInput) JSONSchema() []byte {
	return schemaFileInput
}

// JSONSchema returns the JSON Schema for FileInputOutput.
func (FileInputOutput) JSONSchema() []byte {
	return schemaFileInputOutput
}

// JSONSchema returns the JSON Schema for FileInputSpec.
func (FileInputSpec) JSONSchema() []byte {
	return schemaFileInputSpec
}
